#!/bin/bash

# Batch script for opening firefox

# Positional Args
#    -s [string]  for search
#    -f [nickname] for favourites. if nickname not in list, make new


# Probably have an external dictionary of favorites with nicknames, and we
# want to get that filepath here
# Access file, and search for matches
# if no match, say No matches in database for this nickname. New favorite? Y/N"
#   if n, then quit
#   if y, then say set URL: [URL] (make sure to parse out leading spaces)
	# add new nickname to dictionary and say [nickname] added to Favorites!
#if match, open that webpage



usage="........\n..FFOX..\n........\n\n\n It's firefox with some pizzaz. \n\n\t \n USAGE \n.......\n\n\t [-h] print this help text \n\t [-r] print a reverend quote \n\t [-s term] search term in duckduckgo. \n\t [-f name [url]] open webpage name or create favorite webpage name;url in favorites.\n"
chars=abcdefghijklmnopqrztuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
target="https://duckduckgo.com/"
new_window=false
favorites="${FFOX_PATH}/favorites.txt"
while getopts "ns?hrf" opt; do # parse command line
        case "$opt" in
		n) # set new window to true
			new_window=true
			;;
                s) # parse search flag
                        target="https://duckduckgo.com/?t=ffab&q=${2}"
                        ;;

		f) # parse favorites flag
			# check for favorites.txt
			if [ ! -f "${favorites}" ]; then
				echo -e "\nfavorites.txt does not exist!"
				read -p "Create it? [y/n] " resp
				if [ "${resp}" = "y" ]; then
					touch "${favorites.txt}"
					echo "Ok word, created it."
				else
					echo "It's a central feature but okay, suit yourself."
				fi
				exit 0
			fi
			nickname="${2}" # nickname from user
			url="${3}" # url from user
			if [ -z "${nickname}" ]; then # check for empty name
				echo "No name entered. Call with -h flag for help."
				exit 0
			fi

			found=false # keep track of whether name was found
			while IFS= read -r line; do # read through favorites.txt
				parsed=($(echo $line | tr ";" "\n")) # parse line
				txtname="${parsed[0]}" # favorite name in file
				if [ "$nickname" = "${txtname}" ]; then # compare with user input
					target="${parsed[1]}" # if match, grab target
					found=true # mark if found
					break
				fi
			done < "${favorites}"
			if [ "$found" = false ]; then
				echo -e "Could not find nickname ${nickname} in favorites.\n"
				read -p "Add to favorites? [y/n] " resp
				if [ "${resp}" = "y" ]; then
					if [ -z "${url}" ]; then
						echo "Cannot add to favorites without a URL!"
					else
						echo "${nickname};${url}" >> "${favorites}"
						echo -e "\nBet.. Added to favorites!\n"
					fi
				else
					echo -e "\nHeard. Not adding to favorites.\n"
				fi
				target="${url}"
			fi
			;;

		r) # print reverend quote
			echo "I know his blood can make me whole"
			exit 0
			;;

		h) # show help
			echo -e "$usage"
			exit 0
			;;

		?) # huh
			echo "Bro I literally have no idea what you're talking about. I'll open firefox anyway."
                        ;;
        esac
done

disown="& disown"
noout=" 1>/dev/null 2>&1 " #this makes sure that the stdout and stderr go to null

if [ "${target}" == "" ]
then
	firefox --new-tab ||  "${noout}" &
else
	if [ "$new_window" = true ]; then
		firefox --new-window "${target}" || "${noout}" &
	else
		firefox --new-tab "${target}" || "${noout}" &
	fi
fi
